### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by dasu88** [Tichau/FileConverter#382]
**Describe the bug**
Can't Install

**To Reproduce**
1. Just Install

![2024-03-07_092405](https://github.com/Tichau/FileConverter/assets/23251263/527c5c1a-c71d-456b-b5e8-00f0962b4c60)

**Comment by TA2DF** [comment]
Although there is a solution, I also confirm this:

If version 1.2.3 is not already installed on the system, version 2.0 cannot be installed and gives an installation error.

**Comment by zhanlan123** [comment]
msi install log

```
MSI (s) (3C:0C) [09:42:01:400]: Note: 1: 1722 2: InstallShell 3: D:\Program Files\File Converter\FileConverter.exe 4: --register-shell-extension "D:\Program Files\File Converter\FileConverterExtension.dll" 
MSI (s) (3C:0C) [09:42:01:401]: Note: 1: 2205 2:  3: Error 
MSI (s) (3C:0C) [09:42:01:401]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1722 
MSI (c) (58:68) [09:42:01:406]: Note: 1: 2205 2:  3: Error 
MSI (c) (58:68) [09:42:01:406]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 2863 
DEBUG: Error 2863:  The control ErrorIcon on dialog ErrorDlg needs the icon WixUI_Ico_Info in size 32x32, but that size is not available. Loading the first available size
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2863. The arguments are: ErrorDlg, ErrorIcon, WixUI_Ico_Info
Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action InstallShell, location: D:\Program Files\File Converter\FileConverter.exe, command: --register-shell-extension "D:\Program Files\File Converter\FileConverterExtension.dll" 
MSI (s) (3C:0C) [09:44:45:373]: Note: 1: 2205 2:  3: Error 
MSI (s) (3C:0C) [09:44:45:373]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (s) (3C:0C) [09:44:45:373]: Product: File Converter -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action InstallShell, location: D:\Program Files\File Converter\FileConverter.exe, command: --register-shell-extension "D:\Program Files\File Converter\FileConverterExtension.dll" 

Action ended 9:44:45: InstallFinalize. Return value 3.
```

**Comment by dasu88** [comment]
> Although there is a solution, I also confirm this:
> 
> If version 1.2.3 is not already installed on the system, version 2.0 cannot be installed and gives an installation error.

Indeed, I was able to upgrade from version 1.2.3 to 2.0, but it's a strange approach. Regardless, it's now working, and I really like this program. Thank you.

**Comment by TA2DF** [comment]
> Indeed, I was able to upgrade from version 1.2.3 to 2.0, **_but it's a strange approach_**. ... Thank you.

You're welcome...

Since my English is not very good, the error/bug-report/confirmation I presented may have been perceived as like a rule/compulsion due to the incorrect sentence I made.

Actually I should have said it this way (I had a little help from Google translate this time) :)
"If version 1.2.3 isn't already installed on the system, version 2.0 cannot be installing and giving an installation error."

**Comment by Tichau** [comment]
Thanks a lot for the bug report, I'll look into it, it's not intended at all ^^

**Comment by xkonglong** [comment]
> Although there is a solution, I also confirm this:虽然有一个解决方案，但我也确认了这一点：
> 
> If version 1.2.3 is not already installed on the system, version 2.0 cannot be installed and gives an installation error.如果系统上尚未安装版本 1.2.3，则无法安装版本 2.0 并出现安装错误。

but,  I cannot install ver1.2.3  and 2.0
![image](https://github.com/Tichau/FileConverter/assets/9131496/e7583b20-6a18-40dd-8318-b53a3f667fae)
this  error by ver1.2.3

**Comment by Tichau** [comment]
Hello, do you have any files in this folder: `%localappdata%/FileConverter` ? If so can you send them here?
Considering the logs of @zhanlan123, it seems that the installer failed during the registering of the Windows explorer extensions.
Do you have administrator priviledge on your computer ?

**Comment by xkonglong** [comment]
> %localappdata%/FileConverter

[Diagnostics-14h38m44s.zip](https://github.com/Tichau/FileConverter/files/14534511/Diagnostics-14h38m44s.zip)

**Comment by Tichau** [comment]
Can you try this installer and send me the logs again please?
https://www.grosfichiers.com/GRHkS3wRNf7

**Comment by Autumn-one** [comment]
I have also encountered this error

**Comment by Tichau** [comment]
I pushed a version 2.0.1, can you tell me if it fixes the issue?

**Comment by dasu88** [comment]
I tested the direct installation of version 2.0.1 in a virtual environment, but still received a message that the installation was unsuccessful.
![2024-03-11_083815](https://github.com/Tichau/FileConverter/assets/23251263/3e437333-bf47-4520-b319-0fb2be5b070d)
![2024-03-11_084135](https://github.com/Tichau/FileConverter/assets/23251263/16271cb5-0ab2-426e-9e3e-eba60f74c25e)

**Comment by xkonglong** [comment]
me too.

>2024年3月11日 8:44:00
> Diagnostics stored at path 'C:\Users\admin\AppData\Local\FileConverter\Diagnostics-8h44m0s'
> File Converter v2.0.1 (64 bits)
> Retrieve arguments...
> Arg0: D:\MediaTools\File Converter\FileConverter.exe
> Arg1: --register-shell-extension
> Arg2: D:\MediaTools\File Converter\FileConverterExtension.dll
> 
> Load settings...
>

**Comment by xkonglong** [comment]
I type this command:

`FileConverter.exe --register-shell-extension D:\MediaTools\File Converter\FileConverterExtension.dll`

> D:\MediaTools\File Converter>Diagnostics stored at path 'C:\Users\admin\AppData\Local\FileConverter\Diagnostics-8h55m14s'
> File Converter v2.0.1 (64 bits)
> Retrieve arguments...
> Arg0: FileConverter.exe
> Arg1: --register-shell-extension
> Arg2: D:\MediaTools\File
> Arg3: Converter\FileConverterExtension.dll
> 
> Load settings...
> 
> 未经处理的异常:  System.Exception: Can't retrieve file converter registry entry.
>    在 FileConverterExtension.PathHelpers.get_FileConverterRegistryKey()
>    在 FileConverterExtension.PathHelpers.get_FileConverterPath()
>    在 FileConverterExtension.PathHelpers.get_DefaultSettingsFilePath()
>    在 FileConverter.Services.SettingsService.Load()
>    在 FileConverter.Services.SettingsService..ctor()
> --- 引发异常的上一位置中堆栈跟踪的末尾 ---
>    在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    在 Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>    在 Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    在 Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    在 Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    在 Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
>    在 Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
>    在 System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    在 Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
>    在 Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
>    在 CommunityToolkit.Mvvm.DependencyInjection.Ioc.GetRequiredService[T]()
>    在 FileConverter.Application.Initialize()
>    在 FileConverter.Application.OnStartup(StartupEventArgs e)
>    在 System.Windows.Application.<.ctor>b__1_0(Object unused)
>    在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
>    在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
>    在 System.Windows.Threading.DispatcherOperation.Invoke()
>    在 System.Windows.Threading.Dispatcher.ProcessQueue()
>    在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    在 System.Windows.Application.RunDispatcher(Object ignore)
>    在 System.Windows.Application.RunInternal(Window window)
>    在 FileConverter.Application.Main()
> 
> 


OS:  Windows 10 LSTC  21H2

**Comment by digitalcoyote** [comment]
I've got the .msi installer running on chocolatey's test environment and it's currently failing with 2.0.1. I'll try to get an install log and attach it here if that will help.

**Comment by xkonglong** [comment]
In CMD:

> FileConverter.exe
> 
> D:\MediaTools\File Converter>Diagnostics stored at path 'C:\Users\admin\AppData\Local\FileConverter\Diagnostics-9h14m48s'
> File Converter v2.0.1 (64 bits)
> Retrieve arguments...
> Arg0: FileConverter.exe
> 
> Show page Help.

## if  with parameter:


![image](https://github.com/Tichau/FileConverter/assets/9131496/c13e641e-4569-48ac-a9a9-bd01d241ed68)


> FileConverter.exe --version
> 
> D:\MediaTools\File Converter>Diagnostics stored at path 'C:\Users\admin\AppData\Local\FileConverter\Diagnostics-9h16m11s'
> File Converter v2.0.1 (64 bits)
> Retrieve arguments...
> Arg0: FileConverter.exe
> Arg1: --version
> 
> Load settings...
> 
> 未经处理的异常:  System.Exception: Can't retrieve file converter registry entry.
>    在 FileConverterExtension.PathHelpers.get_FileConverterRegistryKey()
>    在 FileConverterExtension.PathHelpers.get_FileConverterPath()
>    在 FileConverterExtension.PathHelpers.get_DefaultSettingsFilePath()
>    在 FileConverter.Services.SettingsService.Load()
>    在 FileConverter.Services.SettingsService..ctor()
> .....

**Comment by Toei79** [comment]
how you do administrator with msi files?

**Comment by Toei79** [comment]
win 11 x64 ,  able to run installing the old version then new one.

**Comment by Tichau** [comment]
Hello, thanks for your report!
In your logs I can see that the Windows registry has not been set up correctly during the install, this is why the end of the installer failed (during the extension registering). I tried a fix, can you tell me if it works with this version : [FixTestVersion](https://www.grosfichiers.com/pbec8hucYhF) ?

**Comment by FabianLoRs** [comment]
File Convert 2.0.1 and:

![win](https://github.com/Tichau/FileConverter/assets/122753033/53e3264f-4f2d-4c9e-a557-885055b73731)

**Comment by FabianLoRs** [comment]
> Hello, thanks for your report! In your logs I can see that the Windows registry has not been set up correctly during the install, this is why the end of the installer failed (during the extension registering). I tried a fix, can you tell me if it works with this version : [FixTestVersion](https://www.grosfichiers.com/pbec8hucYhF) ?

This works, thank.

**Comment by digitalcoyote** [comment]
@Tichau that FixTestVersion seems to work in my test environment as well.

**Comment by Tichau** [comment]
Fixed in version 2.0.2

**Comment by Hellmaxxer** [comment]
This is still happening to me with this version
